import Head from 'next/head'
import Header from '../components/Header'
import Mensagens from '../components/Mensagens'
import react from 'react'

import 'primereact/resources/primereact.css'
import 'primereact/resources/themes/saga-blue/theme.css'
import 'primeicons/primeicons.css'
import styles from '../styles/index.module.css'

export default function Home () {
	const [msgList, setMsgList] = react.useState([])

	react.useEffect(() => {
		setMsgList(() => {
			if (JSON.parse(localStorage.getItem('msgList')).length == 0)
				return [{ msgId: 1, msgTipo: '', msgText: '', msgUrl: {} }]
			else return JSON.parse(localStorage.getItem('msgList'))
		})
	}, [])

	react.useEffect(() => {
		localStorage.setItem('msgList', JSON.stringify(msgList))
	}, [msgList])

	return (
		<>
			<Head>
				<title>Envia Msg - WhatsApp</title>
				{/* <meta name='description' content='Generated by create next app' /> */}
				<link rel='icon' href='/whatsapp.png' />
			</Head>
			<Header />
			<main className={styles.main}>
				<Mensagens msgList={msgList} setMsgList={setMsgList} />
			</main>
			{/* <Footer/> */}
		</>
	)
}
